log:
  level: "info"
  format: "text"
  enableFile: true
  filename: "./logs/ecs_exporter"  # 会生成 logs/ecs_exporter_20231201.log 这样的文件
  maxSize: 100
  maxAge: 7

api:
  endpoint: https://api.example.com/resource
  iam_endpoint: https://iam.example.com
  domain: your_domain
  username: your_username
  password: your_password
  refresh_token_hours: 3
  page_size: 100
